### ISSUE TITLE
Create icons for "Draw" and "Management"

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#10]
Jon

I could give it a try.
Draw - You could have boundary on 3 sides end with rubber band to brush. may not be enough room
Manage - Same outside graphic but a list inside 

Your thoughts?

**Comment by rgleason** [comment]
Maybe just call the plugin  draw_pi  to be simple?

**Comment by jongough** [comment]
I tried to create three icons for this, but to me they are rubbish. There is one for the manager, I tried to make it look a bit like the current route manager, but... The others are for boundaries and points. As more drawing types are allowed the icons need to reflect the particular type, so boundaries are closed, bearing lines (on the todo list) will be straight with, I think, 3 points only, Points could be POI's, dangers, whatevers. I did think about using letters in the icons, but again not really sure.

As to the name of the plugin, I am changing this as I progress. I do need to make sure the stuff I do is identifiably different from the mainline code so that I don't get confused and I don't get unusual effects by accidentally using mainline code. I am still trying to get comfortable with a name and maybe your suggestion is the answer, i.e. remove the 'redundant' ocpn part.

**Comment by rgleason** [comment]
Were you going to change the "draw" icon according to what is selected or have all available in bar?
Do you have a color preferences, that will be what distinguishes the icons as a group.

Draw _pi is simple but I don't think it expresses the full potential of the plugin because there will be more active information integrated....  DrawNav     DrawDR   DrawInfo  DrawPOI DrawVector 

Need something a little more comprehensive with some flexibility.  I think of squiddio as a name and it is completely different.

Maybe a description of the immediate goals, with some additional future features would help with naming it.

**Comment by jongough** [comment]
Currently when you select the drawing icon, by default 'boundary', the cursor will change to a pencil. If you right click 'before' doing any drawing the icon in the tool bar will change to a diamond to represent a 'waypoint' and the cursor will change to a red cross. If you right click again it will change back to a pencil and the icon will change. This is the only way I could implement multiple drawing tools without having some way of non-intrusively interacting with the toolbar. Its not perfect by any means, but it does work. You just have to know about it.

I am not wedded to the name 'Draw...' but it did express what I was attempting in the first instance. As this is still 'alpha' it can be changed to whatever seems more appropriate. However, when it moves to 'beta' I think it will have to be nailed down.

Where do you think the description should be? My original intent was to be able to draw a boundary, hence the code in the original pull request. However, Dave wanted it moved to a plugin, which is where it is now, and with the possibility of doing more stuff. I think I have it going in the direction of a more general tool (I do have to move some of the boundary stuff out of the path class). The plugin now seems to be morphing in the direction Dave wanted, so the description is probably appropriate.

**Comment by rgleason** [comment]
Jon perhaps I should close this?
