### ISSUE TITLE
Editing Boundaries

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#13]
Is this planned or are you going to have us simply delete and redo?
Many of the edits are what we would want with routes.  Insert point, delete point, move point.

**Comment by jongough** [comment]
When I get the right click on the line/point working I will then be allowing editing in the same manner as for routes and waypoints.

**Comment by rgleason** [comment]
Jon,
I have compiled and installed the most recent version and used it. 
Its working well, but there are a couple of things I noticed.
When I delete a point Opencpn bombs often.
I can insert a point and then move it.
When I identify a point to move and then move it, I cant move it again.
I'll continue to mess around with it.
Thanks for the improvements.

**Comment by rgleason** [comment]
Jon, Deleted my git clone of ocpn_draw.  Git clone of opencpn current beta and compiled. It stayed v4.1.412.  Copied opencpn.lib to my new clone of ocpn_draw.  Compiled ocpn_draw. Packaged it with NSIS  "cpack" command. Then installed it into opencpn 4.1.412.  Used no opengl and ran your plugin.

Move Boundary point and Delete Boundary point work fine, but had one crash (could not figure out what it was.

When I tried removing point from boundary I got an incomplete boundary with points and a border that did not encircle. Tried removing more points from boundary and eventuallly crashed.  Will trace further tonight and report.
Then tried

**Comment by jongough** [comment]
Rick,
   There appears to be a problem when a boundary point is moved that the boundary selection may not be updated so that you cannot select the boundary. I also notice that if you remove a boundary point from the boundary it is not set as a standard point, so you cannot delete it using right click. I will investigate, however, I am going to be away for a few days and do not have a development environment I can use, so it will take a little while before a fix is available.

   Interestingly, this issue occurs under windows but not linux (or I have not found it yet). Windows seems more picky about things. I am not sure what is wrong with the toolbar, but I normally get a warning message about it when I create the first boundary point. This appears to be in the mainline ocpn code (may be caused by me, but I don't know).

Jon

**Comment by jongough** [comment]
Boundaries can now be edited
