### ISSUE TITLE
Own boat  must remain inside boundary or point radius or must remain outside?

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#15]
I suppose that is one of the next challenges?

**Comment by jongough** [comment]
I thought that may be a change for the watchdog plugin. When this one is working well enough it may be worth then investigating that.

**Comment by rgleason** [comment]
Jon, I was thinking about this. For example, climatology data and grib files are used by weather_routing.
If draw-pi was to create the boundaries and points with an "inside" or "outside" parameter, and there was a function that exposed the conditions (but perhaps it would already be stored externally in the draw xml file and could be "discovered" by watchman when that plugin is loaded). 

Thus watchman gets the inside and outside conditions and compares own boat location with that data.

One of the questions I have is about how this relates to the routing routines in the main program. I don't know enough to know if there is a better way to handle it, and perhaps bdcat, pavel and sean should think about it a little too.

**Comment by rgleason** [comment]
Changed title a little to simplify.  We do not know the best way to implement this, whether the inside outside conditions should be in Watchdog or not.

**Comment by jongough** [comment]
I tend to think that this plugin can issue information about boundaries, but does not really want to check for this type of stuff. It could have an API that would allow another plugin to ask questions of items under its control, rather like the 'selectable item' code currently implemented for the rollover info box and the ability to right click and double click to get to properties or information.

**Comment by jongough** [comment]
I have added a JSON message that can provide plugins with the GUID of a boundary if a lat/lon is inside the boundary. I created a patch for the watchdog plugin to demonstrate it working. I think Sean D' is now working on incorporating that into the watchdog so that more comprehensive anchor alarms can be used. I think it could also be used to make sure you are not going to hit something by being able to create boundaries and have the watchdog check if the predictor line is in a boundary and raise an alarm. 

Will need to wait and see what Sean comes up with.

**Comment by rgleason** [comment]
Awesome Jon.

**Comment by jongough** [comment]
This has been implemented now with patch 540 and an update that has been submitted to the watchdog plugin.

**Comment by jongough** [comment]
Can this now be closed?

**Comment by rgleason** [comment]
Works. Thanks Jon
