### ISSUE TITLE
DR Function

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#274]
Jon, First of all this plugin is getting to be exceptional. Thank you.

I just compiled the most recent successfully, then went to your Release area and you really do use and set that up nicely. Thankyou, I wish others knew how to do this. It is quite easy to read and understand.

I beginning to use the new version, two early things.
1. DR doesnt seem to be working for me. Is it for you?
2. I had another idea (so many), what about extending the EBL with offset features like the PIL? I think they would complement each other and EBL is offset lines would be very useful.
Thanks again.

**Comment by jongough** [comment]
Hi Rick,
   I have just tried the DR function and it is working for me on Linux, I will try latter on Windows. Remember with DR you have to left click on the cart to bring up the dialogue box that lets you put in the parameters for the DR line to be drawn.

I am not sure I understand the EBL with offset, that is a PIL isn't it? The EBL does have a perpendicular index line, selectable by a checkbox in the properties, that draws a line perpendicular to the EBL at the end. It was done when I was investigating how to draw a PIL. Can you explain further what you are thinking of when you want an offset? Is it that you want the whole line offset from the boat (starting point), or is it something completely different? Also, how is that going to work without confusing the users? 

Thanks for the compliment.

Jon

**Comment by rgleason** [comment]
Jeez,  I plumb forgot a Right Click!!  So sorry.

Maybe if there's a left click, with that DR menu up it should say "Use 
left click" if it does not cause any other problems?

Best

Rick

**Comment by jongough** [comment]
All tools are selected using right click to cycle and left click to use. The DR is unusual in that it brings up a dialogue box rather than start drawing. The mouse pointer will be a red cross when the DR tool is selected. Once you have filled in the DR box and clicked OK or hit enter the DR specified will be drawn and you will either left click to create a new DR or right click to end using the tool.

Jon

**Comment by rgleason** [comment]
Note: It was a first use after compiling it that I noticed this.
All tools are selected using right click to cycle and left click to use. 
   -click on draw toolbar, right click cycles, yes. left click uses.
The DR is unusual in that it brings up a dialogue box rather than start drawing. 
   - DR box did not come up the first use. Left clicks did not bring it up. Now it does.
The mouse pointer will be a red cross when the DR tool is selected. 
  - Yes.
Once you have filled in the DR box and clicked OK or hit enter the DR specified will be drawn and you will either left click to create a new DR or right click to end using the tool.
  -Yes
You can right click on any DR point and pick move DR point.
I would like to select move "DR line"  which move the DR line.
  If there is a check in Creation box for "Keep DR path length"  the DR Line can only be rotated
if not, the DR line can be relocated anywhere and the path length will change.

PIL & EBL Both start at the boat. 

PIL allows creating offset lines.
Add index 
Move PIL point
can't "Pick a new start point"
Index line - Move line

EBL allows
Pick a new start point.
Move EBL point
Center on moving boat
Move start point to boat lat/long
 - Perpendicular line
 - VRM line

Would adding
Add index
Move index line
Delete index line

Make EBL too complicated?  You could then drop PIL.

**Comment by jongough** [comment]
I have tried with a clean opencpn.conf file but the DR still works for me under linux. I am not sure why a new compile would cause it not to work the first time unless the box is there but off of the screen so that you cannot see it. The second try 'may' then use coordinates for the box so it 'may' then be viewable. The dialogue box does stay where you put it, if you move it, so that the next invocation it pops up in the same location.

The PIL is an extension of the EBL. I kept them separate as it seems a different tool looking at the examples given when it was requested. I am not really sure there should even be a perpendicular line on the EBL, but I built it whilst trying to understand the PIL, so I left it in. If I put too many options on a single tool it confuses people and it makes the properties dialogue big (fixable with tabs, but....).

I can easily allow the PIL to be moved from the boat and have a starting point (it does use an EBL as its base class so has all the capability of an EBL).

**Comment by rgleason** [comment]
.. unless the box is there but off of the screen so that you cannot see it.  <--Likely.  I will try to notice this.
I know this version is new and I had cleaned out the opencpn.ini of everything.

..If I put too many options on a single tool it confuses people and it makes the properties dialogue big   <--This is a consideration. True and you've had the feedback about it.

RE perpendicular for PIL probably not so important.  However for EBL perpendicular I have a request. When right click on the perpendicular line be able to select "Move line perpendicular" and the EBL stay pointed in the same direction and its end point moves with the perpendicular line which is being moved perpendicular.

RE PIL - I can easily allow the PIL to be moved from the boat and have a starting point (it does use an EBL as its base class so has all the capability of an EBL).  <--That would be good!

Thanks for listening.

**Comment by jongough** [comment]
Currently the Perpendicular line is not selectable, it is just a line. If you move the EBL end point does this not do what you want, i.e. the perpendicular line moves with the end point and stays perpendicular to the EBL itself. Or are you suggesting that dragging the Perpendicular line so that the EBL does not change its orientation but the line, and the end point, move closer to or further away from the start of the EBL? If that is the case I 'may' be able to do it the same way as latitude and longitude move locking occurs, i.e. the use of Ctrl or Shift. I could try Ctrl+Shift to lock the EBL angle which would allow the Perpendicular line to move in and out with respect to the start point.

**Comment by rgleason** [comment]
> Or are you suggesting that dragging the Perpendicular line so that the EBL does not change its orientation but the line, and the end point, move closer to or further away from the start of the EBL? If that is the case I 'may' be able to do it the same way as latitude and longitude move locking occurs, i.e. the use of Ctrl or Shift. I could try Ctrl+Shift to lock the EBL angle which would allow the Perpendicular line to move in and out with respect to the start point.

Yes that is what I mean?

**Comment by jongough** [comment]
Try patch 1.3.30. It now allows you to move a PIL the same as you can for an EBL. I have also added a new constraint for an EBL. If you hold the Ctrl+Shift key at the same time and then move the EBL end point it will maintain its angle and just move the end point closer or further away from the start point. Hope this is what you wanted.

**Comment by rgleason** [comment]
Jon, I'll try this tomorrow. Thanks.

**Comment by jongough** [comment]
Have all the options now been covered and are they all working for you? If so, can we close this issues?

Ta

**Comment by rgleason** [comment]
> 
 If you hold the Ctrl+Shift key at the same time and then move the EBL end point it will maintain its angle and just move the end point closer or further away from the start point. Hope this is what you wanted.
> 

Perfect, it works great.

Do you mind leaving this up so I can summarize some of these operational points and check the docs?
Thanks.

**Comment by jongough** [comment]
No, you can leave it up for the time being.

**Comment by rgleason** [comment]
I am closing this now.
