### ISSUE TITLE
Feature Request - Import GPX files for anchorages in croatia

### ISSUE THREAD

**Issue by jobe39** [jongough/ocpn_draw_pi#386]
Hi,

there is a nice site showing all anchorages in croatia with buoys (including prices for buoys). There is also a gpx file that can be downloaded: http://www.anchoragesincroatia.net/p/map-download.html

I have seen that there is already some functionality for importing gpx files. Unfortunately it does not do anything on my installation, when I try to import this gpx file (at least on my mac installation).
Please let me know, if there is some possibility to import such files, or if it might be part of a future version of this plugin.

many thanks.

**Comment by jobe39** [comment]
For those who might need it - I have created a small python file that converts above gpx file to a xml representation that can be imported in the draw plugin.

**Comment by rgleason** [comment]
You state that Guid's are created by the script?  Is that true?
I think that is a problem. Guid's must remain unique.

**Comment by jobe39** [comment]
Yes - is there a way to import without guids? I did not test that. But for the file generated, the guids are unique of corse.

**Comment by rgleason** [comment]
No, they must be unique in Opencpn!!!!!
I am not able to advise re this. Perhaps Jon will.
OpenCPN will import GPX fine!
Why not import to a layer?  
Also doesn't Ocpn_draw support import of GPX?  It is pretty universal format.
---Yes Ocpn_draw does. I just checked.  Try putting your points on an Ocpn_layer. (I don't know if you will have to import them each time, but ideally you should not have to.) 
This will keep that data separate from Wpts.
Advise how it goes.

**Comment by rgleason** [comment]
PS: We can host your croatia gpx on the wiki.

**Comment by jongough** [comment]
OD export/import is currently 'based' on gpx, however, the gpx definitions do not support any of the object types used by OD. In the initial implementation the gpx format was followed, but the whole file was an 'extension' to gpx. You will find that OCPN uses extensions to express some of its data, well OD did that as well, but there was no data that wasn't and extension. So the file now contains all the extension bits without the gpx header and the <extension></extension> parts. 

As there is now confusion I may have to either rename the export/import to 'xml' (perhaps), or put the redundant coding back in. What this means is that you cannot import into OD a standard gpx file as it does not contain any information that OD can use.

If you import an OD gpx file it will be put into a temporary layer which will not be persistent over restarts. If you put the OD gpx file into the user directory this will be loaded into OD when OD loads (either on start of OCPN or when enabled from the plugin's section of the OCPN options dialog).

For OD 1.5 I have implemented a simplistic CSV import process to make it easier to build boundaries in a spreadsheet and then save that as a CSV. This is a very basic implementation and has not been really tested yet. OD 1.5 is the alpha/beta version for the next 'production' version of OD, i.e. 1.6.

OD is a drawing tool for OCPN, it is not intended to be anything else. For importing the anchorages you 'could' convert a real gpx file into an OD 'gpx like' file, i.e. from gpx <wpt ...> to <opencpn:ODPoint ...> . You 'could' convert an <rte> to <opencpn:path><opencpn:type>Boundary</opencpn:type>, but you have to remember that boundaries have the start point and end point being the same ODPoint so that the boundary can be 'closed' which a route is not.

I have added in OD 1.5 a new API for creating boundaries, boundary points and text points. The text point API was built to help with the 'squiddio' plugin and the use of text points rather than opencpn waypoints for points of interest. After all text points were designed to have extra information displayable about points of interest. However, as yet, the squiddio developer has not shown interest in this capability preferring to keep using opencpn waypoints. 

As OD 1.5 is currently a work in progress extra import/export capabilities can be added, but it may take a little while.

Regards
  Jon

**Comment by mauroc** [comment]
"The text point API was built to help with the 'squiddio' plugin and the use of text points rather than opencpn waypoints for points of interest. 
I have been meaning to transition the squiddio plugin to using OD where possible for sometime but have not been able to get around to it due to lack of time. I agree it would be better than using waypoints. I'll look into it in the near future. 
Mauro

**Comment by jongough** [comment]
Hi Mauro,
   As OD 1.5 is currently a 'work in progress' it is not suitable for real use, OD 1.6 will provide that. However, as the ODAPI/JSON messaging will need to be extended to handle what is required it is the correct place/time to work on using text point for squiddo. I just need to know what you really need as currently I have taken a guess and built the first part.

    I also seem to have been a bit distracted lately and have not had the time I would have liked to progress OD 1.5 as far as I would like.

Regards
   Jon

**Comment by jobe39** [comment]
Ok - I have removed guid generation in the script, since it is no needed for the import anyways.

@jongough - Thanks for explanation. That is exactly what my script does - convert a standard gpx file to the format used by opencpn draw. Works nice now.

**Comment by rgleason** [comment]
Added at the bottom of the wiki.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:safety:odraw1.4_pi#croatia_anchorages_script

**Comment by rgleason** [comment]
Isn't this completed by v1.5.14?   Perhaps it can be closed by Jon or jobe

**Comment by jobe39** [comment]
Thanks for the reminder - rgleason. I am closing this issue.
